Add query type generation support
brightinteractive/bright-js-framework pull request #33
Opened 2017-12-07 13:42 UTC by chrisdevereux

2017-12-07 16:10 UTC, Cowbacca commented on src/cli/local-commands/build.command.ts
> +  const plugins = {
Is there duplicate code between this and the run command?

2017-12-07 16:13 UTC, Cowbacca submitted a review, later dismissed

2017-12-07 16:18 UTC, richard-hulm requested changes
'run' and 'build' both seem to be magic - in terms of when you're writing a PluginConfig, it's not indicated to the developer that they're able to add these functions.

A) They won't know they can do it
B) They may implement these methods unknowingly and then be confused why it's running a lot

Ignoring documentation, is it possible to embed this information into the typesystem somehow? So when you look at a pluginConfig you have to override a onPluginRun() method which is run called as a hook?

2017-12-11 09:44 UTC, Cowbacca approved these changes

2017-12-11 10:08 UTC, richard-hulm approved these changes

2017-12-11 10:08 UTC, merged